services:
    schedule:
        container_name: insurance_schedule
        build:
            context: ./
            dockerfile: Dockerfile.schedule
        restart: on-failure
        env_file:
            - .venv/.env
        volumes:
            - insurance_volume:/data

    prices:
        container_name: insurance_prices
        build:
            context: .
            dockerfile: Dockerfile.prices
        restart: on-failure
        env_file:
            - .venv/.env
        volumes:
            - insurance_volume:/data


volumes:
    insurance_volume:
        external: true
